### ISSUE TITLE
Investigate SpecifiedHeading not working for auton

### ISSUE THREAD

**Issue by nickfrisch** [Team302/2023ChargedUp#125]
In auton, when setting heading option in primitive, chassis will not go to specified heading

**Comment by witcpalek** [comment]
@SierraManriquez @Tan560 Is this still an issue?

**Comment by Tan560** [comment]
No once we figured out how to use pathweaver the correct way to make paths we were able to turn the PIDs down and be pretty accurate even while turning. We can close this issue
