### ISSUE TITLE
Verify Arm/Extender State Control in Auton

### ISSUE THREAD

**Issue by Tan560** [Team302/2023ChargedUp#240]
Need to verify arm/extender mechanisms can be called from the an auton XML. Debug if needed

**Comment by Tan560** [comment]
@witcpalek  Please add more detail on how to do this.

**Comment by witcpalek** [comment]
Need to add these options to the current auto xml files for each primitive (may need to update the options based on changes to the arm states -- maybe we should just make these CDATA #IMPLIED with a comment to look at the corresponding state manager to get the valid strings)

          arm               ( HOLD_POSITION_ROTATE | MANUAL_ROTATE | 
                              CUBE_BACKROW_ROTATE | CONE_BACKROW_ROTATE | 
                              CUBE_MIDROW_ROTATE | CONE_MIDROW_ROTATE | HUMAN_PLAYER_STATION_ROTATE | STARTING_POSITION_ROTATE | FLOOR_POSITION_ROTATE) "HOLD_POSITION_ROTATE"
          extender          ( HOLD_POSITION_EXTEND | MANUAL_EXTEND_RETRACT | 
                              CUBE_BACKROW_EXTEND | CONE_BACKROW_EXTEND | 
                              CUBE_MIDROW_EXTEND | CONE_MIDROW_EXTEND | HUMAN_PLAYER_STATION_EXTEND | STARTING_POSITION_EXTEND | FLOOR_EXTEND) "HOLD_POSITION_EXTEND"
          grabber           ( OPEN | GRAB) "OPEN"


So, to test, update Square.xml as follows:


<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>
    <primitive id="RESET_POSITION"
			   pathname="square1.wpilib.json"/>
    <primitive id="DRIVE_PATH"
               pathname="square1.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               time="5.0"
               arm="CUBE_MIDROW_ROTATE"
               extender="CUBE_MIDROW_EXTEND"
               grabber="OPEN"
               />
    <primitive id="DRIVE_PATH"
               pathname="square2.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="90"
               time="5.0"
               arm="STARTING_POSITION_ROTATE "
               extender="STARTING_POSITION_EXTEND "
               grabber="GRAB"
               />
    <primitive id="DRIVE_PATH"
               pathname="square3.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="170"
               time="5.0"
               arm="CONE_BACKROW_ROTATE "
               extender="CONE_BACKROW_EXTEND "
               grabber="OPEN"
               />
    <primitive id="DRIVE_PATH"
               pathname="square4.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="270"
               time="5.0"
               arm="FLOOR_POSITION_ROTATE"
               extender="FLOOR_EXTEND"
               grabber="GRAB"
               />
</auton>

**Comment by witcpalek** [comment]
So, to test, update Square.xml as follows:


<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>
    <primitive id="RESET_POSITION"
			   pathname="square1.wpilib.json"/>
    <primitive id="DRIVE_PATH"
               pathname="square1.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="0"
               time="5.0"
               arm="CUBE_MIDROW_ROTATE"
               extender="CUBE_MIDROW_EXTEND"
               grabber="OPEN"
               />
    <primitive id="DRIVE_PATH"
               pathname="square2.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="90"
               time="5.0"
               arm="STARTING_POSITION_ROTATE "
               extender="STARTING_POSITION_EXTEND "
               grabber="GRAB"
               />
    <primitive id="DRIVE_PATH"
               pathname="square3.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="170"
               time="5.0"
               arm="CONE_BACKROW_ROTATE "
               extender="CONE_BACKROW_EXTEND "
               grabber="OPEN"
               />
    <primitive id="DRIVE_PATH"
               pathname="square4.wpilib.json"
               headingOption="SPECIFIED_ANGLE"
               heading="270"
               time="5.0"
               arm="FLOOR_POSITION_ROTATE"
               extender="FLOOR_EXTEND"
               grabber="GRAB"
               />
</auton>
