### ISSUE TITLE
Update Laptops to 2023 Environment

### ISSUE THREAD

**Issue by witcpalek** [Team302/2023ChargedUp#8]
Add comment indicating when you are done and what laptop you configured and remove yourself as an assignee

**Comment by witcpalek** [comment]
I've updated my laptop

**Comment by JamesLimothy** [comment]
I'm done updating mine

**Comment by witcpalek** [comment]
@JamesLimothy Please indicate the laptop number are using

**Comment by witcpalek** [comment]
@notcharlie2026 you removed you assignment, but didn't indicate the laptop number you are using here

**Comment by nickfrisch** [comment]
My laptop is updated

**Comment by muscatd75** [comment]
Installed on my personal laptop:
1. Updated WPILIB from https://docs.wpilib.org/en/stable/docs/zero-to-robot/step-2/wpilib-setup.html
2. ctre phoenix framework, tuner and hero drivers from https://store.ctr-electronics.com/software/
3. ni package manager, ni software, Driver station, roborio imaging tool  https://www.ni.com/en-us/support/downloads/drivers/download.frc-game-tools.html#473762

**Comment by ElliotBayer** [comment]
I've updated laptop 17

**Comment by nathankeef** [comment]
12 and fire laptop 10

**Comment by ImAPenguin56** [comment]
I updated laptop 18

**Comment by SierraManriquez** [comment]
I updated laptop 14

**Comment by witcpalek** [comment]
removing Mr Hoover and Mr Sinot since they use their own laptops and haven't been around lately

**Comment by witcpalek** [comment]
@Aden25 please complete this item

**Comment by witcpalek** [comment]
Removing Aden as he is working with James and they are sharing laptop 11
