### ISSUE TITLE
Clean up SwerveChassis

### ISSUE THREAD

**Issue by nickfrisch** [Team302/2023ChargedUp#86]
- SwerveChassis has lots of now useless variables from 2022 RapidReact, these need to be removed
- Also remove any pointless or duplicate debugging/logging

**Comment by witcpalek** [comment]
@nickfrisch is this one done?

**Comment by nickfrisch** [comment]
I don't think so.  I think there is still some Rapid React artifacts in the code, like m_shootingDistance in SwerveChassis.h.
